package com.aurospaces.neighbourhood.db.basemodel;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;



import java.util.Date;
import java.math.BigDecimal;


/**
 *
 * @author autogenerated
 */



public class BaseServiceUnitVendor 
{

@Id
@GeneratedValue(strategy=GenerationType.AUTO)
		 /** Field mapping. **/
@Column(name= "id")
protected int id   = 0;

/** Field mapping. **/
@Column(name= "created_time")
protected Date createdTime ;

/** Field mapping. **/
@Column(name= "updated_time")
protected Date updatedTime ;

/** Field mapping. **/
@Column(name= "service_unit_id")
protected int serviceUnitId ;

/** Field mapping. **/
@Column(name= "vendor_id")
protected int vendorId ;

/** Field mapping. **/
@Column(name= "price")
protected BigDecimal price ;

/** Field mapping. **/
@Column(name= "discount")
protected BigDecimal discount ;

/** Field mapping. **/
@Column(name= "label")
protected String label ;

/** Field mapping. **/
@Column(name= "discount_price")
protected BigDecimal discountPrice ;

/** Field mapping. **/
@Column(name= "final_price")
protected BigDecimal finalPrice ;

/** Field mapping. **/
@Column(name= "coupon_discount")
protected int couponDiscount ;

public int getId()
{
  return id;
}
public void setId(final int id)
{
  this.id = id;
}
public Date getCreatedTime()
{
  return createdTime;
}
public void setCreatedTime(final Date createdTime)
{
  this.createdTime = createdTime;
}
public Date getUpdatedTime()
{
  return updatedTime;
}
public void setUpdatedTime(final Date updatedTime)
{
  this.updatedTime = updatedTime;
}
public int getServiceUnitId()
{
  return serviceUnitId;
}
public void setServiceUnitId(final int serviceUnitId)
{
  this.serviceUnitId = serviceUnitId;
}
public int getVendorId()
{
  return vendorId;
}
public void setVendorId(final int vendorId)
{
  this.vendorId = vendorId;
}
public BigDecimal getPrice()
{
  return price;
}
public void setPrice(final BigDecimal price)
{
  this.price = price;
}
public BigDecimal getDiscount()
{
  return discount;
}
public void setDiscount(final BigDecimal discount)
{
  this.discount = discount;
}
public String getLabel()
{
  return label;
}
public void setLabel(final String label)
{
  this.label = label;
}
public BigDecimal getDiscountPrice()
{
  return discountPrice;
}
public void setDiscountPrice(final BigDecimal discountPrice)
{
  this.discountPrice = discountPrice;
}
public BigDecimal getFinalPrice()
{
  return finalPrice;
}
public void setFinalPrice(final BigDecimal finalPrice)
{
  this.finalPrice = finalPrice;
}
public int getCouponDiscount()
{
  return couponDiscount;
}
public void setCouponDiscount(final int couponDiscount)
{
  this.couponDiscount = couponDiscount;
}

}