package com.aurospaces.neighbourhood.db.basemodel;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;



import java.util.Date;
import java.math.BigDecimal;


/**
 *
 * @author autogenerated
 */



public class BaseDoctorType1 
{

@Id
@GeneratedValue(strategy=GenerationType.AUTO)
		 /** Field mapping. **/
@Column(name= "id")
protected int id   = 0;

/** Field mapping. **/
@Column(name= "old_id")
protected String oldId ;

/** Field mapping. **/
@Column(name= "created_time")
protected Date createdTime ;

/** Field mapping. **/
@Column(name= "updated_time")
protected Date updatedTime ;

/** Field mapping. **/
@Column(name= "name")
protected String name ;

/** Field mapping. **/
@Column(name= "price")
protected BigDecimal price ;

/** Field mapping. **/
@Column(name= "discount")
protected BigDecimal discount ;

/** Field mapping. **/
@Column(name= "active")
protected int active ;

public int getId()
{
  return id;
}
public void setId(final int id)
{
  this.id = id;
}
public String getOldId()
{
  return oldId;
}
public void setOldId(final String oldId)
{
  this.oldId = oldId;
}
public Date getCreatedTime()
{
  return createdTime;
}
public void setCreatedTime(final Date createdTime)
{
  this.createdTime = createdTime;
}
public Date getUpdatedTime()
{
  return updatedTime;
}
public void setUpdatedTime(final Date updatedTime)
{
  this.updatedTime = updatedTime;
}
public String getName()
{
  return name;
}
public void setName(final String name)
{
  this.name = name;
}
public BigDecimal getPrice()
{
  return price;
}
public void setPrice(final BigDecimal price)
{
  this.price = price;
}
public BigDecimal getDiscount()
{
  return discount;
}
public void setDiscount(final BigDecimal discount)
{
  this.discount = discount;
}
public int getActive()
{
  return active;
}
public void setActive(final int active)
{
  this.active = active;
}

}