package com.aurospaces.neighbourhood.db.basemodel;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;



import java.util.Date;
import java.math.BigDecimal;


/**
 *
 * @author autogenerated
 */



public class BaseLocation1 
{

@Id
@GeneratedValue(strategy=GenerationType.AUTO)
		 /** Field mapping. **/
@Column(name= "id")
protected int id   = 0;

/** Field mapping. **/
@Column(name= "created_time")
protected Date createdTime ;

/** Field mapping. **/
@Column(name= "updated_time")
protected Date updatedTime ;

/** Field mapping. **/
@Column(name= "name")
protected String name ;

/** Field mapping. **/
@Column(name= "description")
protected String description ;

/** Field mapping. **/
@Column(name= "old_id")
protected String oldId ;

/** Field mapping. **/
@Column(name= "display_order")
protected int displayOrder ;

/** Field mapping. **/
@Column(name= "parent_city")
protected int parentCity ;

/** Field mapping. **/
@Column(name= "is_dummy")
protected int isDummy ;

/** Field mapping. **/
@Column(name= "is_bold")
protected int isBold ;

/** Field mapping. **/
@Column(name= "active")
protected int active ;

/** Field mapping. **/
@Column(name= "is_default")
protected int isDefault ;

/** Field mapping. **/
@Column(name= "latitude")
protected double latitude ;

/** Field mapping. **/
@Column(name= "longitude")
protected double longitude ;

public int getId()
{
  return id;
}
public void setId(final int id)
{
  this.id = id;
}
public Date getCreatedTime()
{
  return createdTime;
}
public void setCreatedTime(final Date createdTime)
{
  this.createdTime = createdTime;
}
public Date getUpdatedTime()
{
  return updatedTime;
}
public void setUpdatedTime(final Date updatedTime)
{
  this.updatedTime = updatedTime;
}
public String getName()
{
  return name;
}
public void setName(final String name)
{
  this.name = name;
}
public String getDescription()
{
  return description;
}
public void setDescription(final String description)
{
  this.description = description;
}
public String getOldId()
{
  return oldId;
}
public void setOldId(final String oldId)
{
  this.oldId = oldId;
}
public int getDisplayOrder()
{
  return displayOrder;
}
public void setDisplayOrder(final int displayOrder)
{
  this.displayOrder = displayOrder;
}
public int getParentCity()
{
  return parentCity;
}
public void setParentCity(final int parentCity)
{
  this.parentCity = parentCity;
}
public int getIsDummy()
{
  return isDummy;
}
public void setIsDummy(final int isDummy)
{
  this.isDummy = isDummy;
}
public int getIsBold()
{
  return isBold;
}
public void setIsBold(final int isBold)
{
  this.isBold = isBold;
}
public int getActive()
{
  return active;
}
public void setActive(final int active)
{
  this.active = active;
}
public int getIsDefault()
{
  return isDefault;
}
public void setIsDefault(final int isDefault)
{
  this.isDefault = isDefault;
}
public double getLatitude()
{
  return latitude;
}
public void setLatitude(final double latitude)
{
  this.latitude = latitude;
}
public double getLongitude()
{
  return longitude;
}
public void setLongitude(final double longitude)
{
  this.longitude = longitude;
}

}