package com.aurospaces.neighbourhood.db.basemodel;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;



import java.util.Date;
import java.math.BigDecimal;


/**
 *
 * @author autogenerated
 */



public class BaseAutoPriceMeater 
{

@Id
@GeneratedValue(strategy=GenerationType.AUTO)
		 /** Field mapping. **/
@Column(name= "id")
protected int id   = 0;

/** Field mapping. **/
@Column(name= "created_time")
protected Date createdTime ;

/** Field mapping. **/
@Column(name= "updated_time")
protected Date updatedTime ;

/** Field mapping. **/
@Column(name= "generated_id")
protected String generatedId ;

/** Field mapping. **/
@Column(name= "start_time")
protected double startTime ;

/** Field mapping. **/
@Column(name= "end_time")
protected double endTime ;

/** Field mapping. **/
@Column(name= "message")
protected String message ;

/** Field mapping. **/
@Column(name= "vendor_id")
protected int vendor_id ;

public int getId() {
	return id;
}

public void setId(int id) {
	this.id = id;
}

public Date getCreatedTime() {
	return createdTime;
}

public void setCreatedTime(Date createdTime) {
	this.createdTime = createdTime;
}

public Date getUpdatedTime() {
	return updatedTime;
}

public void setUpdatedTime(Date updatedTime) {
	this.updatedTime = updatedTime;
}

public String getGeneratedId() {
	return generatedId;
}

public void setGeneratedId(String generatedId) {
	this.generatedId = generatedId;
}

public double getStartTime() {
	return startTime;
}

public void setStartTime(double startTime) {
	this.startTime = startTime;
}

public double getEndTime() {
	return endTime;
}

public void setEndTime(double endTime) {
	this.endTime = endTime;
}

public String getMessage() {
	return message;
}

public void setMessage(String message) {
	this.message = message;
}

public int getVendor_id() {
	return vendor_id;
}

public void setVendor_id(int vendor_id) {
	this.vendor_id = vendor_id;
}

}