package com.aurospaces.neighbourhood.db.basemodel;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;



import java.util.Date;
import java.math.BigDecimal;


/**
 *
 * @author autogenerated
 */



public class BaseLocationService1 
{

@Id
@GeneratedValue(strategy=GenerationType.AUTO)
		 /** Field mapping. **/
@Column(name= "id")
protected int id   = 0;

/** Field mapping. **/
@Column(name= "created_time")
protected Date createdTime ;

/** Field mapping. **/
@Column(name= "updated_time")
protected Date updatedTime ;

/** Field mapping. **/
@Column(name= "location_id")
protected int locationId ;

/** Field mapping. **/
@Column(name= "service_id")
protected int serviceId ;

/** Field mapping. **/
@Column(name= "display_order")
protected int displayOrder ;

public int getId()
{
  return id;
}
public void setId(final int id)
{
  this.id = id;
}
public Date getCreatedTime()
{
  return createdTime;
}
public void setCreatedTime(final Date createdTime)
{
  this.createdTime = createdTime;
}
public Date getUpdatedTime()
{
  return updatedTime;
}
public void setUpdatedTime(final Date updatedTime)
{
  this.updatedTime = updatedTime;
}
public int getLocationId()
{
  return locationId;
}
public void setLocationId(final int locationId)
{
  this.locationId = locationId;
}
public int getServiceId()
{
  return serviceId;
}
public void setServiceId(final int serviceId)
{
  this.serviceId = serviceId;
}
public int getDisplayOrder()
{
  return displayOrder;
}
public void setDisplayOrder(final int displayOrder)
{
  this.displayOrder = displayOrder;
}

}