package com.aurospaces.neighbourhood.db.basemodel;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;



import java.util.Date;
import java.math.BigDecimal;


/**
 *
 * @author autogenerated
 */



public class BaseVendor1 
{

@Id
@GeneratedValue(strategy=GenerationType.AUTO)
		 /** Field mapping. **/
@Column(name= "id")
protected int id   = 0;

/** Field mapping. **/
@Column(name= "created_time")
protected Date createdTime ;

/** Field mapping. **/
@Column(name= "updated_time")
protected Date updatedTime ;

/** Field mapping. **/
@Column(name= "old_id")
protected String oldId ;

/** Field mapping. **/
@Column(name= "first_name")
protected String firstName ;

/** Field mapping. **/
@Column(name= "last_name")
protected String lastName ;

/** Field mapping. **/
@Column(name= "father_name")
protected String fatherName ;

/** Field mapping. **/
@Column(name= "gender")
protected String gender ;

/** Field mapping. **/
@Column(name= "date_of_birth")
protected Date dateOfBirth ;

/** Field mapping. **/
@Column(name= "education")
protected String education ;

/** Field mapping. **/
@Column(name= "languages_known")
protected String languagesKnown ;

/** Field mapping. **/
@Column(name= "address")
protected String address ;

/** Field mapping. **/
@Column(name= "city")
protected String city ;

/** Field mapping. **/
@Column(name= "pin")
protected String pin ;

/** Field mapping. **/
@Column(name= "state")
protected String state ;

/** Field mapping. **/
@Column(name= "land_mark")
protected String landMark ;

/** Field mapping. **/
@Column(name= "pan_number")
protected String panNumber ;

/** Field mapping. **/
@Column(name= "mobile_number")
protected String mobileNumber ;

/** Field mapping. **/
@Column(name= "reference_number")
protected String referenceNumber ;

/** Field mapping. **/
@Column(name= "email")
protected String email ;

/** Field mapping. **/
@Column(name= "native_state")
protected String nativeState ;

/** Field mapping. **/
@Column(name= "photograph")
protected String photograph ;

/** Field mapping. **/
@Column(name= "id_proof")
protected String idProof ;

/** Field mapping. **/
@Column(name= "address_proof")
protected String addressProof ;

/** Field mapping. **/
@Column(name= "parent_category1")
protected String parentCategory1 ;

/** Field mapping. **/
@Column(name= "parent_category2")
protected String parentCategory2 ;

/** Field mapping. **/
@Column(name= "sub_category1")
protected String subCategory1 ;

/** Field mapping. **/
@Column(name= "sub_category2")
protected String subCategory2 ;

/** Field mapping. **/
@Column(name= "qualification")
protected String qualification ;

/** Field mapping. **/
@Column(name= "certifications")
protected String certifications ;

/** Field mapping. **/
@Column(name= "company")
protected String company ;

/** Field mapping. **/
@Column(name= "employees")
protected String employees ;

/** Field mapping. **/
@Column(name= "portfolio_files")
protected String portfolioFiles ;

/** Field mapping. **/
@Column(name= "video_files")
protected String videoFiles ;

/** Field mapping. **/
@Column(name= "mou")
protected String mou ;

/** Field mapping. **/
@Column(name= "commercials")
protected String commercials ;

/** Field mapping. **/
@Column(name= "serving_country")
protected String servingCountry ;

/** Field mapping. **/
@Column(name= "serving_state")
protected String servingState ;

/** Field mapping. **/
@Column(name= "serving_city")
protected int servingCity ;

/** Field mapping. **/
@Column(name= "serving_location")
protected String servingLocation ;

/** Field mapping. **/
@Column(name= "accholder_name")
protected String accholderName ;

/** Field mapping. **/
@Column(name= "account_number")
protected String accountNumber ;

/** Field mapping. **/
@Column(name= "bank_name")
protected String bankName ;

/** Field mapping. **/
@Column(name= "ifsc_code")
protected String ifscCode ;

/** Field mapping. **/
@Column(name= "branch_name")
protected String branchName ;

/** Field mapping. **/
@Column(name= "latitude")
protected double latitude ;

/** Field mapping. **/
@Column(name= "longitude")
protected double longitude ;

/** Field mapping. **/
@Column(name= "cluster_id")
protected int clusterId ;

/** Field mapping. **/
@Column(name= "map_icon")
protected String mapIcon ;

/** Field mapping. **/
@Column(name= "weightage")
protected double weightage ;

/** Field mapping. **/
@Column(name= "preference")
protected double preference ;

/** Field mapping. **/
@Column(name= "password")
protected String password ;

public int getId()
{
  return id;
}
public void setId(final int id)
{
  this.id = id;
}
public Date getCreatedTime()
{
  return createdTime;
}
public void setCreatedTime(final Date createdTime)
{
  this.createdTime = createdTime;
}
public Date getUpdatedTime()
{
  return updatedTime;
}
public void setUpdatedTime(final Date updatedTime)
{
  this.updatedTime = updatedTime;
}
public String getOldId()
{
  return oldId;
}
public void setOldId(final String oldId)
{
  this.oldId = oldId;
}
public String getFirstName()
{
  return firstName;
}
public void setFirstName(final String firstName)
{
  this.firstName = firstName;
}
public String getLastName()
{
  return lastName;
}
public void setLastName(final String lastName)
{
  this.lastName = lastName;
}
public String getFatherName()
{
  return fatherName;
}
public void setFatherName(final String fatherName)
{
  this.fatherName = fatherName;
}
public String getGender()
{
  return gender;
}
public void setGender(final String gender)
{
  this.gender = gender;
}
public Date getDateOfBirth()
{
  return dateOfBirth;
}
public void setDateOfBirth(final Date dateOfBirth)
{
  this.dateOfBirth = dateOfBirth;
}
public String getEducation()
{
  return education;
}
public void setEducation(final String education)
{
  this.education = education;
}
public String getLanguagesKnown()
{
  return languagesKnown;
}
public void setLanguagesKnown(final String languagesKnown)
{
  this.languagesKnown = languagesKnown;
}
public String getAddress()
{
  return address;
}
public void setAddress(final String address)
{
  this.address = address;
}
public String getCity()
{
  return city;
}
public void setCity(final String city)
{
  this.city = city;
}
public String getPin()
{
  return pin;
}
public void setPin(final String pin)
{
  this.pin = pin;
}
public String getState()
{
  return state;
}
public void setState(final String state)
{
  this.state = state;
}
public String getLandMark()
{
  return landMark;
}
public void setLandMark(final String landMark)
{
  this.landMark = landMark;
}
public String getPanNumber()
{
  return panNumber;
}
public void setPanNumber(final String panNumber)
{
  this.panNumber = panNumber;
}
public String getMobileNumber()
{
  return mobileNumber;
}
public void setMobileNumber(final String mobileNumber)
{
  this.mobileNumber = mobileNumber;
}
public String getReferenceNumber()
{
  return referenceNumber;
}
public void setReferenceNumber(final String referenceNumber)
{
  this.referenceNumber = referenceNumber;
}
public String getEmail()
{
  return email;
}
public void setEmail(final String email)
{
  this.email = email;
}
public String getNativeState()
{
  return nativeState;
}
public void setNativeState(final String nativeState)
{
  this.nativeState = nativeState;
}
public String getPhotograph()
{
  return photograph;
}
public void setPhotograph(final String photograph)
{
  this.photograph = photograph;
}
public String getIdProof()
{
  return idProof;
}
public void setIdProof(final String idProof)
{
  this.idProof = idProof;
}
public String getAddressProof()
{
  return addressProof;
}
public void setAddressProof(final String addressProof)
{
  this.addressProof = addressProof;
}
public String getParentCategory1()
{
  return parentCategory1;
}
public void setParentCategory1(final String parentCategory1)
{
  this.parentCategory1 = parentCategory1;
}
public String getParentCategory2()
{
  return parentCategory2;
}
public void setParentCategory2(final String parentCategory2)
{
  this.parentCategory2 = parentCategory2;
}
public String getSubCategory1()
{
  return subCategory1;
}
public void setSubCategory1(final String subCategory1)
{
  this.subCategory1 = subCategory1;
}
public String getSubCategory2()
{
  return subCategory2;
}
public void setSubCategory2(final String subCategory2)
{
  this.subCategory2 = subCategory2;
}
public String getQualification()
{
  return qualification;
}
public void setQualification(final String qualification)
{
  this.qualification = qualification;
}
public String getCertifications()
{
  return certifications;
}
public void setCertifications(final String certifications)
{
  this.certifications = certifications;
}
public String getCompany()
{
  return company;
}
public void setCompany(final String company)
{
  this.company = company;
}
public String getEmployees()
{
  return employees;
}
public void setEmployees(final String employees)
{
  this.employees = employees;
}
public String getPortfolioFiles()
{
  return portfolioFiles;
}
public void setPortfolioFiles(final String portfolioFiles)
{
  this.portfolioFiles = portfolioFiles;
}
public String getVideoFiles()
{
  return videoFiles;
}
public void setVideoFiles(final String videoFiles)
{
  this.videoFiles = videoFiles;
}
public String getMou()
{
  return mou;
}
public void setMou(final String mou)
{
  this.mou = mou;
}
public String getCommercials()
{
  return commercials;
}
public void setCommercials(final String commercials)
{
  this.commercials = commercials;
}
public String getServingCountry()
{
  return servingCountry;
}
public void setServingCountry(final String servingCountry)
{
  this.servingCountry = servingCountry;
}
public String getServingState()
{
  return servingState;
}
public void setServingState(final String servingState)
{
  this.servingState = servingState;
}
public int getServingCity()
{
  return servingCity;
}
public void setServingCity(final int servingCity)
{
  this.servingCity = servingCity;
}
public String getServingLocation()
{
  return servingLocation;
}
public void setServingLocation(final String servingLocation)
{
  this.servingLocation = servingLocation;
}
public String getAccholderName()
{
  return accholderName;
}
public void setAccholderName(final String accholderName)
{
  this.accholderName = accholderName;
}
public String getAccountNumber()
{
  return accountNumber;
}
public void setAccountNumber(final String accountNumber)
{
  this.accountNumber = accountNumber;
}
public String getBankName()
{
  return bankName;
}
public void setBankName(final String bankName)
{
  this.bankName = bankName;
}
public String getIfscCode()
{
  return ifscCode;
}
public void setIfscCode(final String ifscCode)
{
  this.ifscCode = ifscCode;
}
public String getBranchName()
{
  return branchName;
}
public void setBranchName(final String branchName)
{
  this.branchName = branchName;
}
public double getLatitude()
{
  return latitude;
}
public void setLatitude(final double latitude)
{
  this.latitude = latitude;
}
public double getLongitude()
{
  return longitude;
}
public void setLongitude(final double longitude)
{
  this.longitude = longitude;
}
public int getClusterId()
{
  return clusterId;
}
public void setClusterId(final int clusterId)
{
  this.clusterId = clusterId;
}
public String getMapIcon()
{
  return mapIcon;
}
public void setMapIcon(final String mapIcon)
{
  this.mapIcon = mapIcon;
}
public double getWeightage()
{
  return weightage;
}
public void setWeightage(final double weightage)
{
  this.weightage = weightage;
}
public double getPreference()
{
  return preference;
}
public void setPreference(final double preference)
{
  this.preference = preference;
}
public String getPassword()
{
  return password;
}
public void setPassword(final String password)
{
  this.password = password;
}

}