package com.aurospaces.neighbourhood.db.basemodel;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;



import java.util.Date;
import java.math.BigDecimal;


/**
 *
 * @author autogenerated
 */



public class BaseAdminDiscount 
{

@Id
@GeneratedValue(strategy=GenerationType.AUTO)
		 /** Field mapping. **/
@Column(name= "id")
protected int id   = 0;

/** Field mapping. **/
@Column(name= "created_time")
protected Date createdTime ;

/** Field mapping. **/
@Column(name= "updated_time")
protected Date updatedTime ;

/** Field mapping. **/
@Column(name= "title")
protected String title ;

/** Field mapping. **/
@Column(name= "percentage")
protected double percentage ;

/** Field mapping. **/
@Column(name= "amount")
protected double amount ;

public int getId()
{
  return id;
}
public void setId(final int id)
{
  this.id = id;
}
public Date getCreatedTime()
{
  return createdTime;
}
public void setCreatedTime(final Date createdTime)
{
  this.createdTime = createdTime;
}
public Date getUpdatedTime()
{
  return updatedTime;
}
public void setUpdatedTime(final Date updatedTime)
{
  this.updatedTime = updatedTime;
}
public String getTitle()
{
  return title;
}
public void setTitle(final String title)
{
  this.title = title;
}
public double getPercentage()
{
  return percentage;
}
public void setPercentage(final double percentage)
{
  this.percentage = percentage;
}
public double getAmount()
{
  return amount;
}
public void setAmount(final double amount)
{
  this.amount = amount;
}

}