package com.aurospaces.neighbourhood.db.basemodel;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;



import java.util.Date;
import java.math.BigDecimal;


/**
 *
 * @author autogenerated
 */



public class BaseOrderSymptom1 
{

@Id
@GeneratedValue(strategy=GenerationType.AUTO)
		 /** Field mapping. **/
@Column(name= "id")
protected int id   = 0;

/** Field mapping. **/
@Column(name= "created_time")
protected Date createdTime ;

/** Field mapping. **/
@Column(name= "updated_time")
protected Date updatedTime ;

/** Field mapping. **/
@Column(name= "order_id")
protected int orderId ;

/** Field mapping. **/
@Column(name= "generated_order_id")
protected String generatedOrderId ;

/** Field mapping. **/
@Column(name= "old_symptom_id")
protected String oldSymptomId ;

/** Field mapping. **/
@Column(name= "symptom_id")
protected int symptomId ;

public int getId()
{
  return id;
}
public void setId(final int id)
{
  this.id = id;
}
public Date getCreatedTime()
{
  return createdTime;
}
public void setCreatedTime(final Date createdTime)
{
  this.createdTime = createdTime;
}
public Date getUpdatedTime()
{
  return updatedTime;
}
public void setUpdatedTime(final Date updatedTime)
{
  this.updatedTime = updatedTime;
}
public int getOrderId()
{
  return orderId;
}
public void setOrderId(final int orderId)
{
  this.orderId = orderId;
}
public String getGeneratedOrderId()
{
  return generatedOrderId;
}
public void setGeneratedOrderId(final String generatedOrderId)
{
  this.generatedOrderId = generatedOrderId;
}
public String getOldSymptomId()
{
  return oldSymptomId;
}
public void setOldSymptomId(final String oldSymptomId)
{
  this.oldSymptomId = oldSymptomId;
}
public int getSymptomId()
{
  return symptomId;
}
public void setSymptomId(final int symptomId)
{
  this.symptomId = symptomId;
}

}