package com.aurospaces.neighbourhood.db.basemodel;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;



import java.util.Date;
import java.math.BigDecimal;


/**
 *
 * @author autogenerated
 */



public class BaseVendorStatus 
{

@Id
@GeneratedValue(strategy=GenerationType.AUTO)
		 /** Field mapping. **/
@Column(name= "id")
protected int id   = 0;

/** Field mapping. **/
@Column(name= "statusname")
protected String statusname ;

public int getId()
{
  return id;
}
public void setId(final int id)
{
  this.id = id;
}
public String getStatusname()
{
  return statusname;
}
public void setStatusname(final String statusname)
{
  this.statusname = statusname;
}

}