package com.aurospaces.neighbourhood.db.basemodel;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;



import java.util.Date;
import java.math.BigDecimal;


/**
 *
 * @author autogenerated
 */



public class BaseOrderInfo1 
{

@Id
@GeneratedValue(strategy=GenerationType.AUTO)
		 /** Field mapping. **/
@Column(name= "id")
protected int id   = 0;

/** Field mapping. **/
@Column(name= "created_time")
protected Date createdTime ;

/** Field mapping. **/
@Column(name= "updated_time")
protected Date updatedTime ;

/** Field mapping. **/
@Column(name= "generated_id")
protected String generatedId ;

/** Field mapping. **/
@Column(name= "booked_date")
protected Date bookedDate ;

/** Field mapping. **/
@Column(name= "appointment_date")
protected Date appointmentDate ;

/** Field mapping. **/
@Column(name= "appointment_slot_old_id")
protected String appointmentSlotOldId ;

/** Field mapping. **/
@Column(name= "appointment_slot_id")
protected int appointmentSlotId ;

/** Field mapping. **/
@Column(name= "status_id")
protected int statusId ;

/** Field mapping. **/
@Column(name= "contact_number")
protected String contactNumber ;

/** Field mapping. **/
@Column(name= "contact_email")
protected String contactEmail ;

/** Field mapping. **/
@Column(name= "address")
protected String address ;

/** Field mapping. **/
@Column(name= "total_price")
protected BigDecimal totalPrice ;

/** Field mapping. **/
@Column(name= "total_discount")
protected BigDecimal totalDiscount ;

/** Field mapping. **/
@Column(name= "net_amount")
protected BigDecimal netAmount ;

/** Field mapping. **/
@Column(name= "description")
protected String description ;

/** Field mapping. **/
@Column(name= "gender")
protected String gender ;

/** Field mapping. **/
@Column(name= "service_id")
protected int serviceId ;

/** Field mapping. **/
@Column(name= "vendor_id")
protected int vendorId ;

/** Field mapping. **/
@Column(name= "sub_category")
protected int subCategory ;

/** Field mapping. **/
@Column(name= "is_new_customer")
protected int isNewCustomer ;

/** Field mapping. **/
@Column(name= "location_id")
protected int locationId ;

/** Field mapping. **/
@Column(name= "latitude")
protected double latitude ;

/** Field mapping. **/
@Column(name= "longitude")
protected double longitude ;

/** Field mapping. **/
@Column(name= "coupon_code")
protected String couponCode ;

/** Field mapping. **/
@Column(name= "is_admin_order")
protected int isAdminOrder ;

/** Field mapping. **/
@Column(name= "user_id")
protected int userId ;

/** Field mapping. **/
@Column(name= "watsup_location")
protected String watsupLocation ;

/** Field mapping. **/
@Column(name= "priority")
protected String priority ;

/** Field mapping. **/
@Column(name= "customer_name")
protected String customerName ;

/** Field mapping. **/
@Column(name= "client_order_id")
protected String clientOrderId ;

/** Field mapping. **/
@Column(name= "vendor_service_charge")
protected double vendorServiceCharge ;

/** Field mapping. **/
@Column(name= "goods_charge")
protected double goodsCharge ;

/** Field mapping. **/
@Column(name= "margin_value")
protected double marginValue ;

/** Field mapping. **/
@Column(name= "no_of_hours_work")
protected int noOfHoursWork ;

/** Field mapping. **/
@Column(name= "transportaion_charge")
protected double transportaionCharge ;

/** Field mapping. **/
@Column(name= "no_of_visits")
protected int noOfVisits ;

/** Field mapping. **/
@Column(name= "fixed_charge")
protected double fixedCharge ;

/** Field mapping. **/
@Column(name= "auro_log_id")
protected int auroLogId ;

/** Field mapping. **/
@Column(name= "client_log_id")
protected int clientLogId ;

/** Field mapping. **/
@Column(name= "invoice_file")
protected String invoiceFile ;

/** Field mapping. **/
@Column(name= "feedback_form")
protected String feedbackForm ;

/** Field mapping. **/
@Column(name= "region_id")
protected int regionId ;

/** Field mapping. **/
@Column(name= "auro_log")
protected String auroLog ;

/** Field mapping. **/
@Column(name= "client_log")
protected String clientLog ;

/** Field mapping. **/
@Column(name= "goodsName")
protected String goodsName ;

/** Field mapping. **/
@Column(name= "goodPaidBy")
protected String goodPaidBy ;

/** Field mapping. **/
@Column(name= "vendor_status")
protected int vendorStatus ;

/** Field mapping. **/
@Column(name= "no_bhk")
protected String noBhk ;

/** Field mapping. **/
@Column(name= "completionDate")
protected Date completionDate ;

/** Field mapping. **/
@Column(name= "billingto")
protected String billingto ;

/** Field mapping. **/
@Column(name= "ownername")
protected String ownername ;

/** Field mapping. **/
@Column(name= "isPause")
protected int isPause ;

/** Field mapping. **/
@Column(name= "kissantax")
protected int kissantax ;

/** Field mapping. **/
@Column(name= "sestax")
protected int sestax ;

/** Field mapping. **/
@Column(name= "sbstax")
protected int sbstax ;

/** Field mapping. **/
@Column(name= "invoice_date")
protected Date invoiceDate ;

public int getId()
{
  return id;
}
public void setId(final int id)
{
  this.id = id;
}
public Date getCreatedTime()
{
  return createdTime;
}
public void setCreatedTime(final Date createdTime)
{
  this.createdTime = createdTime;
}
public Date getUpdatedTime()
{
  return updatedTime;
}
public void setUpdatedTime(final Date updatedTime)
{
  this.updatedTime = updatedTime;
}
public String getGeneratedId()
{
  return generatedId;
}
public void setGeneratedId(final String generatedId)
{
  this.generatedId = generatedId;
}
public Date getBookedDate()
{
  return bookedDate;
}
public void setBookedDate(final Date bookedDate)
{
  this.bookedDate = bookedDate;
}
public Date getAppointmentDate()
{
  return appointmentDate;
}
public void setAppointmentDate(final Date appointmentDate)
{
  this.appointmentDate = appointmentDate;
}
public String getAppointmentSlotOldId()
{
  return appointmentSlotOldId;
}
public void setAppointmentSlotOldId(final String appointmentSlotOldId)
{
  this.appointmentSlotOldId = appointmentSlotOldId;
}
public int getAppointmentSlotId()
{
  return appointmentSlotId;
}
public void setAppointmentSlotId(final int appointmentSlotId)
{
  this.appointmentSlotId = appointmentSlotId;
}
public int getStatusId()
{
  return statusId;
}
public void setStatusId(final int statusId)
{
  this.statusId = statusId;
}
public String getContactNumber()
{
  return contactNumber;
}
public void setContactNumber(final String contactNumber)
{
  this.contactNumber = contactNumber;
}
public String getContactEmail()
{
  return contactEmail;
}
public void setContactEmail(final String contactEmail)
{
  this.contactEmail = contactEmail;
}
public String getAddress()
{
  return address;
}
public void setAddress(final String address)
{
  this.address = address;
}
public BigDecimal getTotalPrice()
{
  return totalPrice;
}
public void setTotalPrice(final BigDecimal totalPrice)
{
  this.totalPrice = totalPrice;
}
public BigDecimal getTotalDiscount()
{
  return totalDiscount;
}
public void setTotalDiscount(final BigDecimal totalDiscount)
{
  this.totalDiscount = totalDiscount;
}
public BigDecimal getNetAmount()
{
  return netAmount;
}
public void setNetAmount(final BigDecimal netAmount)
{
  this.netAmount = netAmount;
}
public String getDescription()
{
  return description;
}
public void setDescription(final String description)
{
  this.description = description;
}
public String getGender()
{
  return gender;
}
public void setGender(final String gender)
{
  this.gender = gender;
}
public int getServiceId()
{
  return serviceId;
}
public void setServiceId(final int serviceId)
{
  this.serviceId = serviceId;
}
public int getVendorId()
{
  return vendorId;
}
public void setVendorId(final int vendorId)
{
  this.vendorId = vendorId;
}
public int getSubCategory()
{
  return subCategory;
}
public void setSubCategory(final int subCategory)
{
  this.subCategory = subCategory;
}
public int getIsNewCustomer()
{
  return isNewCustomer;
}
public void setIsNewCustomer(final int isNewCustomer)
{
  this.isNewCustomer = isNewCustomer;
}
public int getLocationId()
{
  return locationId;
}
public void setLocationId(final int locationId)
{
  this.locationId = locationId;
}
public double getLatitude()
{
  return latitude;
}
public void setLatitude(final double latitude)
{
  this.latitude = latitude;
}
public double getLongitude()
{
  return longitude;
}
public void setLongitude(final double longitude)
{
  this.longitude = longitude;
}
public String getCouponCode()
{
  return couponCode;
}
public void setCouponCode(final String couponCode)
{
  this.couponCode = couponCode;
}
public int getIsAdminOrder()
{
  return isAdminOrder;
}
public void setIsAdminOrder(final int isAdminOrder)
{
  this.isAdminOrder = isAdminOrder;
}
public int getUserId()
{
  return userId;
}
public void setUserId(final int userId)
{
  this.userId = userId;
}
public String getWatsupLocation()
{
  return watsupLocation;
}
public void setWatsupLocation(final String watsupLocation)
{
  this.watsupLocation = watsupLocation;
}
public String getPriority()
{
  return priority;
}
public void setPriority(final String priority)
{
  this.priority = priority;
}
public String getCustomerName()
{
  return customerName;
}
public void setCustomerName(final String customerName)
{
  this.customerName = customerName;
}
public String getClientOrderId()
{
  return clientOrderId;
}
public void setClientOrderId(final String clientOrderId)
{
  this.clientOrderId = clientOrderId;
}
public double getVendorServiceCharge()
{
  return vendorServiceCharge;
}
public void setVendorServiceCharge(final double vendorServiceCharge)
{
  this.vendorServiceCharge = vendorServiceCharge;
}
public double getGoodsCharge()
{
  return goodsCharge;
}
public void setGoodsCharge(final double goodsCharge)
{
  this.goodsCharge = goodsCharge;
}
public double getMarginValue()
{
  return marginValue;
}
public void setMarginValue(final double marginValue)
{
  this.marginValue = marginValue;
}
public int getNoOfHoursWork()
{
  return noOfHoursWork;
}
public void setNoOfHoursWork(final int noOfHoursWork)
{
  this.noOfHoursWork = noOfHoursWork;
}
public double getTransportaionCharge()
{
  return transportaionCharge;
}
public void setTransportaionCharge(final double transportaionCharge)
{
  this.transportaionCharge = transportaionCharge;
}
public int getNoOfVisits()
{
  return noOfVisits;
}
public void setNoOfVisits(final int noOfVisits)
{
  this.noOfVisits = noOfVisits;
}
public double getFixedCharge()
{
  return fixedCharge;
}
public void setFixedCharge(final double fixedCharge)
{
  this.fixedCharge = fixedCharge;
}
public int getAuroLogId()
{
  return auroLogId;
}
public void setAuroLogId(final int auroLogId)
{
  this.auroLogId = auroLogId;
}
public int getClientLogId()
{
  return clientLogId;
}
public void setClientLogId(final int clientLogId)
{
  this.clientLogId = clientLogId;
}
public String getInvoiceFile()
{
  return invoiceFile;
}
public void setInvoiceFile(final String invoiceFile)
{
  this.invoiceFile = invoiceFile;
}
public String getFeedbackForm()
{
  return feedbackForm;
}
public void setFeedbackForm(final String feedbackForm)
{
  this.feedbackForm = feedbackForm;
}
public int getRegionId()
{
  return regionId;
}
public void setRegionId(final int regionId)
{
  this.regionId = regionId;
}
public String getAuroLog()
{
  return auroLog;
}
public void setAuroLog(final String auroLog)
{
  this.auroLog = auroLog;
}
public String getClientLog()
{
  return clientLog;
}
public void setClientLog(final String clientLog)
{
  this.clientLog = clientLog;
}
public String getGoodsName()
{
  return goodsName;
}
public void setGoodsName(final String goodsName)
{
  this.goodsName = goodsName;
}
public String getGoodPaidBy()
{
  return goodPaidBy;
}
public void setGoodPaidBy(final String goodPaidBy)
{
  this.goodPaidBy = goodPaidBy;
}
public int getVendorStatus()
{
  return vendorStatus;
}
public void setVendorStatus(final int vendorStatus)
{
  this.vendorStatus = vendorStatus;
}
public String getNoBhk()
{
  return noBhk;
}
public void setNoBhk(final String noBhk)
{
  this.noBhk = noBhk;
}
public Date getCompletionDate()
{
  return completionDate;
}
public void setCompletionDate(final Date completionDate)
{
  this.completionDate = completionDate;
}
public String getBillingto()
{
  return billingto;
}
public void setBillingto(final String billingto)
{
  this.billingto = billingto;
}
public String getOwnername()
{
  return ownername;
}
public void setOwnername(final String ownername)
{
  this.ownername = ownername;
}
public int getIsPause()
{
  return isPause;
}
public void setIsPause(final int isPause)
{
  this.isPause = isPause;
}
public int getKissantax()
{
  return kissantax;
}
public void setKissantax(final int kissantax)
{
  this.kissantax = kissantax;
}
public int getSestax()
{
  return sestax;
}
public void setSestax(final int sestax)
{
  this.sestax = sestax;
}
public int getSbstax()
{
  return sbstax;
}
public void setSbstax(final int sbstax)
{
  this.sbstax = sbstax;
}
public Date getInvoiceDate()
{
  return invoiceDate;
}
public void setInvoiceDate(final Date invoiceDate)
{
  this.invoiceDate = invoiceDate;
}

}