package com.aurospaces.neighbourhood.db.basemodel;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;



import java.util.Date;
import java.math.BigDecimal;


/**
 *
 * @author autogenerated
 */



public class BaseUserRole 
{

/** Field mapping. **/
@Column(name= "roleId")
protected int roleId ;

/** Field mapping. **/
@Column(name= "userId")
protected String userId ;

public int getRoleId()
{
  return roleId;
}
public void setRoleId(final int roleId)
{
  this.roleId = roleId;
}
public String getUserId()
{
  return userId;
}
public void setUserId(final String userId)
{
  this.userId = userId;
}

}