package com.aurospaces.neighbourhood.db.basemodel;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;



import java.util.Date;
import java.math.BigDecimal;


/**
 *
 * @author autogenerated
 */



public class BaseClientTransactions 
{

@Id
@GeneratedValue(strategy=GenerationType.AUTO)
		 /** Field mapping. **/
@Column(name= "id")
protected int id   = 0;

/** Field mapping. **/
@Column(name= "created_time")
protected Date createdTime ;

/** Field mapping. **/
@Column(name= "updated_time")
protected Date updatedTime ;

/** Field mapping. **/
@Column(name= "client_id")
protected int clientId ;

/** Field mapping. **/
@Column(name= "ac_number")
protected int acNumber ;

/** Field mapping. **/
@Column(name= "bank_name")
protected String bankName ;

/** Field mapping. **/
@Column(name= "branch_name")
protected String branchName ;

/** Field mapping. **/
@Column(name= "ifsc_code")
protected String ifscCode ;

/** Field mapping. **/
@Column(name= "transaction_date")
protected Date transactionDate ;

/** Field mapping. **/
@Column(name= "amount")
protected int amount ;

public int getId()
{
  return id;
}
public void setId(final int id)
{
  this.id = id;
}
public Date getCreatedTime()
{
  return createdTime;
}
public void setCreatedTime(final Date createdTime)
{
  this.createdTime = createdTime;
}
public Date getUpdatedTime()
{
  return updatedTime;
}
public void setUpdatedTime(final Date updatedTime)
{
  this.updatedTime = updatedTime;
}
public int getClientId()
{
  return clientId;
}
public void setClientId(final int clientId)
{
  this.clientId = clientId;
}
public int getAcNumber()
{
  return acNumber;
}
public void setAcNumber(final int acNumber)
{
  this.acNumber = acNumber;
}
public String getBankName()
{
  return bankName;
}
public void setBankName(final String bankName)
{
  this.bankName = bankName;
}
public String getBranchName()
{
  return branchName;
}
public void setBranchName(final String branchName)
{
  this.branchName = branchName;
}
public String getIfscCode()
{
  return ifscCode;
}
public void setIfscCode(final String ifscCode)
{
  this.ifscCode = ifscCode;
}
public Date getTransactionDate()
{
  return transactionDate;
}
public void setTransactionDate(final Date transactionDate)
{
  this.transactionDate = transactionDate;
}
public int getAmount()
{
  return amount;
}
public void setAmount(final int amount)
{
  this.amount = amount;
}

}