package com.aurospaces.neighbourhood.db.basemodel;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;



import java.util.Date;
import java.math.BigDecimal;


/**
 *
 * @author autogenerated
 */



public class BaseService1 
{

@Id
@GeneratedValue(strategy=GenerationType.AUTO)
		 /** Field mapping. **/
@Column(name= "id")
protected int id   = 0;

/** Field mapping. **/
@Column(name= "created_time")
protected Date createdTime ;

/** Field mapping. **/
@Column(name= "updated_time")
protected Date updatedTime ;

/** Field mapping. **/
@Column(name= "name")
protected String name ;

/** Field mapping. **/
@Column(name= "description")
protected String description ;

/** Field mapping. **/
@Column(name= "parent_category")
protected String parentCategory ;

/** Field mapping. **/
@Column(name= "old_id")
protected String oldId ;

/** Field mapping. **/
@Column(name= "page_name")
protected String pageName ;

/** Field mapping. **/
@Column(name= "display_text")
protected String displayText ;

/** Field mapping. **/
@Column(name= "img_url")
protected String imgUrl ;

/** Field mapping. **/
@Column(name= "display_order")
protected int displayOrder ;

/** Field mapping. **/
@Column(name= "is_bold")
protected int isBold ;

/** Field mapping. **/
@Column(name= "is_dummy")
protected int isDummy ;

/** Field mapping. **/
@Column(name= "active")
protected int active ;

/** Field mapping. **/
@Column(name= "popup_message")
protected String popupMessage ;

/** Field mapping. **/
@Column(name= "keywords")
protected String keywords ;

public int getId()
{
  return id;
}
public void setId(final int id)
{
  this.id = id;
}
public Date getCreatedTime()
{
  return createdTime;
}
public void setCreatedTime(final Date createdTime)
{
  this.createdTime = createdTime;
}
public Date getUpdatedTime()
{
  return updatedTime;
}
public void setUpdatedTime(final Date updatedTime)
{
  this.updatedTime = updatedTime;
}
public String getName()
{
  return name;
}
public void setName(final String name)
{
  this.name = name;
}
public String getDescription()
{
  return description;
}
public void setDescription(final String description)
{
  this.description = description;
}
public String getParentCategory()
{
  return parentCategory;
}
public void setParentCategory(final String parentCategory)
{
  this.parentCategory = parentCategory;
}
public String getOldId()
{
  return oldId;
}
public void setOldId(final String oldId)
{
  this.oldId = oldId;
}
public String getPageName()
{
  return pageName;
}
public void setPageName(final String pageName)
{
  this.pageName = pageName;
}
public String getDisplayText()
{
  return displayText;
}
public void setDisplayText(final String displayText)
{
  this.displayText = displayText;
}
public String getImgUrl()
{
  return imgUrl;
}
public void setImgUrl(final String imgUrl)
{
  this.imgUrl = imgUrl;
}
public int getDisplayOrder()
{
  return displayOrder;
}
public void setDisplayOrder(final int displayOrder)
{
  this.displayOrder = displayOrder;
}
public int getIsBold()
{
  return isBold;
}
public void setIsBold(final int isBold)
{
  this.isBold = isBold;
}
public int getIsDummy()
{
  return isDummy;
}
public void setIsDummy(final int isDummy)
{
  this.isDummy = isDummy;
}
public int getActive()
{
  return active;
}
public void setActive(final int active)
{
  this.active = active;
}
public String getPopupMessage()
{
  return popupMessage;
}
public void setPopupMessage(final String popupMessage)
{
  this.popupMessage = popupMessage;
}
public String getKeywords()
{
  return keywords;
}
public void setKeywords(final String keywords)
{
  this.keywords = keywords;
}

}