package com.aurospaces.neighbourhood.db.basemodel;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;



import java.util.Date;


/**
 *
 * @author autogenerated
 */



public class BaseCustomer1 
{

@Id
@GeneratedValue(strategy=GenerationType.AUTO)
		 /** Field mapping. **/
@Column(name= "id")
protected int id   = 0;

/** Field mapping. **/
@Column(name= "created_time")
protected Date createdTime ;

/** Field mapping. **/
@Column(name= "updated_time")
protected Date updatedTime ;

/** Field mapping. **/
@Column(name= "name")
protected String name ;

/** Field mapping. **/
@Column(name= "mobile_number")
protected String mobileNumber ;

/** Field mapping. **/
@Column(name= "email")
protected String email ;

/** Field mapping. **/
@Column(name= "address1")
protected String address1 ;

/** Field mapping. **/
@Column(name= "city")
protected String city ;

/** Field mapping. **/
@Column(name= "pincode")
protected String pincode ;

/** Field mapping. **/
@Column(name= "state")
protected String state ;

/** Field mapping. **/
@Column(name= "password")
protected String password ;

/** Field mapping. **/
@Column(name= "old_id")
protected String oldId ;

public int getId()
{
  return id;
}
public void setId(final int id)
{
  this.id = id;
}
public Date getCreatedTime()
{
  return createdTime;
}
public void setCreatedTime(final Date createdTime)
{
  this.createdTime = createdTime;
}
public Date getUpdatedTime()
{
  return updatedTime;
}
public void setUpdatedTime(final Date updatedTime)
{
  this.updatedTime = updatedTime;
}
public String getName()
{
  return name;
}
public void setName(final String name)
{
  this.name = name;
}
public String getMobileNumber()
{
  return mobileNumber;
}
public void setMobileNumber(final String mobileNumber)
{
  this.mobileNumber = mobileNumber;
}
public String getEmail()
{
  return email;
}
public void setEmail(final String email)
{
  this.email = email;
}
public String getAddress1()
{
  return address1;
}
public void setAddress1(final String address1)
{
  this.address1 = address1;
}
public String getCity()
{
  return city;
}
public void setCity(final String city)
{
  this.city = city;
}
public String getPincode()
{
  return pincode;
}
public void setPincode(final String pincode)
{
  this.pincode = pincode;
}
public String getState()
{
  return state;
}
public void setState(final String state)
{
  this.state = state;
}
public String getPassword()
{
  return password;
}
public void setPassword(final String password)
{
  this.password = password;
}
public String getOldId()
{
  return oldId;
}
public void setOldId(final String oldId)
{
  this.oldId = oldId;
}

}