package com.aurospaces.neighbourhood.db.basemodel;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;



import java.util.Date;
import java.math.BigDecimal;


/**
 *
 * @author autogenerated
 */



public class BaseCouponCode 
{

@Id
@GeneratedValue(strategy=GenerationType.AUTO)
		 /** Field mapping. **/
@Column(name= "id")
protected int id   = 0;

/** Field mapping. **/
@Column(name= "base_code")
protected String baseCode ;

/** Field mapping. **/
@Column(name= "display_text1")
protected String displayText1 ;

/** Field mapping. **/
@Column(name= "display_text2")
protected String displayText2 ;

/** Field mapping. **/
@Column(name= "created_time")
protected Date createdTime ;

/** Field mapping. **/
@Column(name= "updated_time")
protected Date updatedTime ;

/** Field mapping. **/
@Column(name= "amount")
protected double amount ;

/** Field mapping. **/
@Column(name= "number_times")
protected int numberTimes ;

/** Field mapping. **/
@Column(name= "total_count")
protected int totalCount ;

/** Field mapping. **/
@Column(name= "expiry_time")
protected Date expiryTime ;

public int getId()
{
  return id;
}
public void setId(final int id)
{
  this.id = id;
}
public String getBaseCode()
{
  return baseCode;
}
public void setBaseCode(final String baseCode)
{
  this.baseCode = baseCode;
}
public String getDisplayText1()
{
  return displayText1;
}
public void setDisplayText1(final String displayText1)
{
  this.displayText1 = displayText1;
}
public String getDisplayText2()
{
  return displayText2;
}
public void setDisplayText2(final String displayText2)
{
  this.displayText2 = displayText2;
}
public Date getCreatedTime()
{
  return createdTime;
}
public void setCreatedTime(final Date createdTime)
{
  this.createdTime = createdTime;
}
public Date getUpdatedTime()
{
  return updatedTime;
}
public void setUpdatedTime(final Date updatedTime)
{
  this.updatedTime = updatedTime;
}
public double getAmount()
{
  return amount;
}
public void setAmount(final double amount)
{
  this.amount = amount;
}
public int getNumberTimes()
{
  return numberTimes;
}
public void setNumberTimes(final int numberTimes)
{
  this.numberTimes = numberTimes;
}
public int getTotalCount()
{
  return totalCount;
}
public void setTotalCount(final int totalCount)
{
  this.totalCount = totalCount;
}
public Date getExpiryTime()
{
  return expiryTime;
}
public void setExpiryTime(final Date expiryTime)
{
  this.expiryTime = expiryTime;
}

}