package com.aurospaces.neighbourhood.db.basemodel;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;



import java.util.Date;
import java.math.BigDecimal;


/**
 *
 * @author autogenerated
 */



public class BaseCoupon 
{

@Id
@GeneratedValue(strategy=GenerationType.AUTO)
		 /** Field mapping. **/
@Column(name= "id")
protected int id   = 0;

/** Field mapping. **/
@Column(name= "coupon_code_id")
protected int couponCodeId ;

/** Field mapping. **/
@Column(name= "code")
protected String code ;

/** Field mapping. **/
@Column(name= "vendor_code")
protected String vendorCode ;

/** Field mapping. **/
@Column(name= "created_time")
protected Date createdTime ;

/** Field mapping. **/
@Column(name= "updated_time")
protected Date updatedTime ;

/** Field mapping. **/
@Column(name= "redeemed_date")
protected Date redeemedDate ;

/** Field mapping. **/
@Column(name= "sent_date")
protected Date sentDate ;

/** Field mapping. **/
@Column(name= "redeemed")
protected int redeemed ;

/** Field mapping. **/
@Column(name= "sent")
protected int sent ;

/** Field mapping. **/
@Column(name= "redeemed_by")
protected int redeemedBy ;

public int getId()
{
  return id;
}
public void setId(final int id)
{
  this.id = id;
}
public int getCouponCodeId()
{
  return couponCodeId;
}
public void setCouponCodeId(final int couponCodeId)
{
  this.couponCodeId = couponCodeId;
}
public String getCode()
{
  return code;
}
public void setCode(final String code)
{
  this.code = code;
}
public String getVendorCode()
{
  return vendorCode;
}
public void setVendorCode(final String vendorCode)
{
  this.vendorCode = vendorCode;
}
public Date getCreatedTime()
{
  return createdTime;
}
public void setCreatedTime(final Date createdTime)
{
  this.createdTime = createdTime;
}
public Date getUpdatedTime()
{
  return updatedTime;
}
public void setUpdatedTime(final Date updatedTime)
{
  this.updatedTime = updatedTime;
}
public Date getRedeemedDate()
{
  return redeemedDate;
}
public void setRedeemedDate(final Date redeemedDate)
{
  this.redeemedDate = redeemedDate;
}
public Date getSentDate()
{
  return sentDate;
}
public void setSentDate(final Date sentDate)
{
  this.sentDate = sentDate;
}
public int getRedeemed()
{
  return redeemed;
}
public void setRedeemed(final int redeemed)
{
  this.redeemed = redeemed;
}
public int getSent()
{
  return sent;
}
public void setSent(final int sent)
{
  this.sent = sent;
}
public int getRedeemedBy()
{
  return redeemedBy;
}
public void setRedeemedBy(final int redeemedBy)
{
  this.redeemedBy = redeemedBy;
}

}